apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: yourdockerhub/student-registration-backend
        ports:
        - containerPort: 8080
        env:
          - name: SPRING_DATASOURCE_URL
            value: jdbc:mysql://mysql:3306/studentdb
          - name: SPRING_DATASOURCE_USERNAME
            value: root
          - name: SPRING_DATASOURCE_PASSWORD
            value: root
---

apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: ClusterIP  # Internal only
  selector:
    app: backend
  ports:
    - port: 8080       # Internal service port
      targetPort: 8080 # Container port
            
